export enum Intent {
  CREATE_EVENT = 'CREATE_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  DELETE_EVENT = 'DELETE_EVENT',
  LIST_EVENTS = 'LIST_EVENTS',
  SEARCH_EVENTS = 'SEARCH_EVENTS',
  CHECK_AVAILABILITY = 'CHECK_AVAILABILITY',
  SET_REMINDER = 'SET_REMINDER',
  CANCEL_REMINDER = 'CANCEL_REMINDER',
  UNKNOWN = 'UNKNOWN',
}

export enum EventStatus {
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
}

export enum MessageMode {
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  UPDATE = 'UPDATE',
  QUERY = 'QUERY',
}

export enum MessageStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
  NEED_CLARIFICATION = 'NEED_CLARIFICATION',
}

export enum ReminderStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  CANCELLED = 'CANCELLED',
}

export enum RepeatFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  YEARLY = 'YEARLY',
}
